import type { AppData, EntryType, TabId } from "../types";

export const TYPE_INFO: Record<
	EntryType,
	{
		icon: string;
		label: string;
		plural: string;
		cls: EntryType;
		tag: string;
		color: string;
		view: TabId;
	}
> = {
	exam: {
		icon: "📝",
		label: "Examen",
		plural: "Exámenes",
		cls: "exam",
		tag: "Examen",
		color: "#FF5C5C",
		view: "exams",
	},
	sport: {
		icon: "⚽",
		label: "Deporte",
		plural: "Deportes",
		cls: "sport",
		tag: "Deporte",
		color: "#2DB87C",
		view: "sports",
	},
	event: {
		icon: "🎉",
		label: "Evento",
		plural: "Eventos",
		cls: "event",
		tag: "Evento",
		color: "#7C5CFC",
		view: "events",
	},
	recover: {
		icon: "⚠️",
		label: "Recuperatorio",
		plural: "Recuperar",
		cls: "recover",
		tag: "Recuperar",
		color: "#FF9A00",
		view: "recover",
	},
	work: {
		icon: "📋",
		label: "Trabajo",
		plural: "Trabajos",
		cls: "work",
		tag: "Entrega",
		color: "#0099E6",
		view: "works",
	},
};

export const CALENDAR_TYPE_ORDER: EntryType[] = [
	"exam",
	"sport",
	"event",
	"recover",
	"work",
];

export const TITLE_LABELS: Record<EntryType, string> = {
	exam: "Materia",
	sport: "Deporte / Actividad",
	event: "Descripción del evento",
	recover: "Materia a recuperar",
	work: "Nombre del trabajo",
};

export const DEFAULT_DATA: AppData = {
	entries: [
		{
			id: 1,
			type: "exam",
			kid: "Martín",
			title: "Matemáticas",
			date: "2026-06-20",
			timeFrom: "",
			timeTo: "",
			grade: "",
			notes: "Álgebra y funciones cuadráticas",
			repeatEnabled: false,
			repeatFrom: "",
			repeatTo: "",
			repeatDays: [],
		},
		{
			id: 2,
			type: "exam",
			kid: "Lucía",
			title: "Historia",
			date: "2026-06-19",
			timeFrom: "",
			timeTo: "",
			grade: "",
			notes: "Revolución Francesa hasta Napoleón",
			repeatEnabled: false,
			repeatFrom: "",
			repeatTo: "",
			repeatDays: [],
		},
		{
			id: 3,
			type: "sport",
			kid: "Martín",
			title: "Fútbol — Club Atlético",
			date: "",
			timeFrom: "16:00",
			timeTo: "17:30",
			grade: "",
			notes: "Traer canilleras",
			repeatEnabled: true,
			repeatFrom: "2026-06-01",
			repeatTo: "2026-12-18",
			repeatDays: [1, 3],
		},
		{
			id: 4,
			type: "sport",
			kid: "Lucía",
			title: "Hockey — Club San Martín",
			date: "",
			timeFrom: "09:00",
			timeTo: "10:30",
			grade: "",
			notes: "Sábados a la mañana",
			repeatEnabled: true,
			repeatFrom: "2026-06-01",
			repeatTo: "2026-12-06",
			repeatDays: [6],
		},
		{
			id: 5,
			type: "event",
			kid: "Familia",
			title: "Cumpleaños Abuela Rosa",
			date: "2026-06-21",
			timeFrom: "13:00",
			timeTo: "",
			grade: "",
			notes: "Llevar regalo",
			repeatEnabled: false,
			repeatFrom: "",
			repeatTo: "",
			repeatDays: [],
		},
		{
			id: 6,
			type: "recover",
			kid: "Martín",
			title: "Ciencias Naturales",
			date: "2026-06-25",
			timeFrom: "",
			timeTo: "",
			grade: "4",
			notes: "Recuperatorio en contra-turno",
			repeatEnabled: false,
			repeatFrom: "",
			repeatTo: "",
			repeatDays: [],
		},
		{
			id: 7,
			type: "recover",
			kid: "Lucía",
			title: "Inglés",
			date: "2026-06-24",
			timeFrom: "",
			timeTo: "",
			grade: "5",
			notes: "Reading comprehension",
			repeatEnabled: false,
			repeatFrom: "",
			repeatTo: "",
			repeatDays: [],
		},
		{
			id: 8,
			type: "work",
			kid: "Martín",
			title: "Maqueta Sistema Solar",
			date: "2026-06-22",
			timeFrom: "",
			timeTo: "",
			grade: "",
			notes: "Física — con soporte cartón",
			repeatEnabled: false,
			repeatFrom: "",
			repeatTo: "",
			repeatDays: [],
		},
		{
			id: 9,
			type: "work",
			kid: "Lucía",
			title: 'Informe Novela "Martín Fierro"',
			date: "2026-06-26",
			timeFrom: "",
			timeTo: "",
			grade: "",
			notes: "Lengua — mínimo 3 carillas",
			repeatEnabled: false,
			repeatFrom: "",
			repeatTo: "",
			repeatDays: [],
		},
	],
	nextId: 10,
	shopping: [],
	nextShoppingId: 1,
};
